export function getPresets() {
	return [
		{
			category: 'Smart Play Cue',
			name: 'GO',
			type: 'button',
			style: {
				text: 'GO',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x1b5e20,
			},
			steps: [{ down: [{ actionId: 'go', options: {} }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Previous cue',
			type: 'button',
			style: {
				text: 'PREV',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x283593,
			},
			steps: [{ down: [{ actionId: 'prev', options: {} }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Pause / resume',
			type: 'button',
			style: {
				text: 'PAUSE',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0xe65100,
			},
			steps: [{ down: [{ actionId: 'pause', options: {} }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Play cue',
			type: 'button',
			style: {
				text: 'PLAY\\nCUE',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x2e7d32,
			},
			steps: [{ down: [{ actionId: 'playCue', options: { cueNumber: 1 } }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Stop cue',
			type: 'button',
			style: {
				text: 'STOP',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0xc62828,
			},
			steps: [{ down: [{ actionId: 'stopCue', options: {} }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Mute cue',
			type: 'button',
			style: {
				text: 'MUTE\\nCUE',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0xe65100,
			},
			steps: [{ down: [{ actionId: 'muteCue', options: { cueNumber: 1 } }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Master mute',
			type: 'button',
			style: {
				text: 'MASTER\\nMUTE',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x1565c0,
			},
			steps: [{ down: [{ actionId: 'masterMute', options: {} }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Layer 1 show/hide',
			type: 'button',
			style: {
				text: 'L1\\nSHOW',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x00695c,
			},
			steps: [{ down: [{ actionId: 'layerShow', options: { layer: '1', action: 'toggle' } }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Layer 2 show/hide',
			type: 'button',
			style: {
				text: 'L2\\nSHOW',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x00695c,
			},
			steps: [{ down: [{ actionId: 'layerShow', options: { layer: '2', action: 'toggle' } }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Layer 1 mute',
			type: 'button',
			style: {
				text: 'L1\\nMUTE',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x455a64,
			},
			steps: [{ down: [{ actionId: 'layerMute', options: { layer: '1' } }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Layer 2 mute',
			type: 'button',
			style: {
				text: 'L2\\nMUTE',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x455a64,
			},
			steps: [{ down: [{ actionId: 'layerMute', options: { layer: '2' } }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'Layer 1 blend',
			type: 'button',
			style: {
				text: 'L1\\nBLEND',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x5d4037,
			},
			steps: [{ down: [{ actionId: 'layerBlend', options: { layer: '1', mode: '1' } }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue',
			name: 'PANIC',
			type: 'button',
			style: {
				text: 'PANIC\\n!',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x000000,
			},
			steps: [{ down: [{ actionId: 'panic', options: {} }], up: [] }],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue - Time',
			name: 'Remaining time (HH:MM:SS)',
			type: 'button',
			style: {
				text: '--:--:--',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x222222,
			},
			steps: [],
			feedbacks: [
				{ feedbackId: 'remainingTime', options: {} },
				{ feedbackId: 'timeCritical', options: {} },
			],
		},
		{
			category: 'Smart Play Cue - Time',
			name: 'Current cue',
			type: 'button',
			style: {
				text: 'NO CUE',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x222222,
			},
			steps: [],
			feedbacks: [{ feedbackId: 'currentCue', options: {} }],
		},
		{
			category: 'Smart Play Cue - Time',
			name: 'Hours (HH)',
			type: 'button',
			style: {
				text: 'HH\\n$(smartcue:hh)',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x222222,
			},
			steps: [],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue - Time',
			name: 'Minutes (MM)',
			type: 'button',
			style: {
				text: 'MM\\n$(smartcue:mm)',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x222222,
			},
			steps: [],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue - Time',
			name: 'Seconds (SS)',
			type: 'button',
			style: {
				text: 'SS\\n$(smartcue:ss)',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x222222,
			},
			steps: [],
			feedbacks: [],
		},
		{
			category: 'Smart Play Cue - Time',
			name: 'Status',
			type: 'button',
			style: {
				text: '$(smartcue:status)',
				size: 'auto',
				color: 0xffffff,
				bgcolor: 0x000000,
			},
			steps: [],
			feedbacks: [],
		},
	]
}
